/** PC NieR:Automata SlotData layout constants (aligned with NieREdit). */

export const SAVEFILE_SIZE_BYTES = 235980;

export const SAVEFILE_MONEY_START_BYTE = 197996;
export const SAVEFILE_INVENTORY_START_BYTE = 198000;
export const SAVEFILE_CORPSE_INVENTORY_START_BYTE = 201072;
export const SAVEFILE_WEAPONS_START_BYTE = 204144;
export const SAVEFILE_POD_PROGRAMS_START_BYTE = 205744;
export const SAVEFILE_PLUGIN_CHIPS_START_BYTE = 206012;
export const SAVEFILE_XP_START_BYTE = 231196;

export const MONEY_SIZE_BYTES = 4;
export const XP_SIZE_BYTES = 4;
export const INVENTORY_SIZE_ITEMS = 256;
export const INVENTORY_ITEM_SIZE_BYTES = 12;
export const INVENTORY_SIZE_BYTES =
  INVENTORY_SIZE_ITEMS * INVENTORY_ITEM_SIZE_BYTES;
export const WEAPONS_SIZE_ITEMS = 80;
export const WEAPONS_ITEM_SIZE_BYTES = 20;
export const WEAPONS_SIZE_BYTES = WEAPONS_SIZE_ITEMS * WEAPONS_ITEM_SIZE_BYTES;
export const POD_PROGRAMS_SIZE_ITEMS = 32;
export const POD_PROGRAMS_ITEM_SIZE_BYTES = 8;
export const POD_PROGRAMS_SIZE_BYTES =
  POD_PROGRAMS_SIZE_ITEMS * POD_PROGRAMS_ITEM_SIZE_BYTES;
export const PLUGIN_CHIPS_SIZE_ITEMS = 300;
export const PLUGIN_CHIPS_ITEM_SIZE_BYTES = 48;
export const PLUGIN_CHIPS_SIZE_BYTES =
  PLUGIN_CHIPS_SIZE_ITEMS * PLUGIN_CHIPS_ITEM_SIZE_BYTES;

/** Gap between POD programs end and plug-in chips (NieREdit unknown6). */
export const BETWEEN_POD_AND_CHIPS_START_BYTE =
  SAVEFILE_POD_PROGRAMS_START_BYTE + POD_PROGRAMS_SIZE_BYTES;
export const BETWEEN_POD_AND_CHIPS_SIZE_BYTES =
  SAVEFILE_PLUGIN_CHIPS_START_BYTE - BETWEEN_POD_AND_CHIPS_START_BYTE;

export const BETWEEN_CHIPS_AND_XP_START_BYTE =
  SAVEFILE_PLUGIN_CHIPS_START_BYTE + PLUGIN_CHIPS_SIZE_BYTES;
export const BETWEEN_CHIPS_AND_XP_SIZE_BYTES =
  SAVEFILE_XP_START_BYTE - BETWEEN_CHIPS_AND_XP_START_BYTE;

export const AFTER_XP_START_BYTE = SAVEFILE_XP_START_BYTE + XP_SIZE_BYTES;
export const AFTER_XP_SIZE_BYTES = SAVEFILE_SIZE_BYTES - AFTER_XP_START_BYTE;
