/** PC NieR:Automata SlotData layout constants (aligned with NieREdit). */

export const SAVEFILE_SIZE_BYTES = 235980;

export const SAVEFILE_STEAM_ID_START_BYTE = 4;
export const SAVEFILE_PLAY_TIME_START_BYTE = 36;
export const SAVEFILE_CHARACTER_NAME_START_BYTE = 52;
export const SAVEFILE_MONEY_START_BYTE = 197996;
export const SAVEFILE_INVENTORY_START_BYTE = 198000;
export const SAVEFILE_CORPSE_INVENTORY_START_BYTE = 201072;
export const SAVEFILE_WEAPONS_START_BYTE = 204144;
export const SAVEFILE_POD_PROGRAMS_START_BYTE = 205744;
export const SAVEFILE_PLUGIN_CHIPS_START_BYTE = 206012;
export const SAVEFILE_OUTFIT_CONFIG_START_BYTE = 230364;
export const SAVEFILE_PLAY_RECORDS_START_BYTE = 230744;
export const SAVEFILE_POD_COSMETIC_CONFIG_START_BYTE = 230896;
export const SAVEFILE_HAIR_COLORS_START_BYTE = 231036;
export const SAVEFILE_EMIL_BULLETS_EQUIPPED_BYTE = 231039;
export const SAVEFILE_WEAPON_SLOT_1_START_BYTE = 231156;
export const SAVEFILE_WEAPON_SLOT_2_START_BYTE = 231164;
export const SAVEFILE_XP_START_BYTE = 231196;
export const SAVEFILE_POD_CONFIG_START_BYTE = 231208;
export const SAVEFILE_DEBUG_FLAG_START_BYTE = 234775;

export const STEAM_ID_SIZE_BYTES = 8;
export const PLAY_TIME_SIZE_BYTES = 4;
export const CHARACTER_NAME_SIZE_BYTES = 70;
export const DEBUG_FLAG_SIZE_BYTES = 1;
export const MONEY_SIZE_BYTES = 4;
export const XP_SIZE_BYTES = 4;
export const INVENTORY_SIZE_ITEMS = 256;
export const INVENTORY_ITEM_SIZE_BYTES = 12;
export const INVENTORY_SIZE_BYTES =
  INVENTORY_SIZE_ITEMS * INVENTORY_ITEM_SIZE_BYTES;
export const WEAPONS_SIZE_ITEMS = 80;
export const WEAPONS_ITEM_SIZE_BYTES = 20;
export const WEAPONS_SIZE_BYTES = WEAPONS_SIZE_ITEMS * WEAPONS_ITEM_SIZE_BYTES;
export const POD_PROGRAMS_SIZE_ITEMS = 32;
export const POD_PROGRAMS_ITEM_SIZE_BYTES = 8;
export const POD_PROGRAMS_SIZE_BYTES =
  POD_PROGRAMS_SIZE_ITEMS * POD_PROGRAMS_ITEM_SIZE_BYTES;
export const PLUGIN_CHIPS_SIZE_ITEMS = 300;
export const PLUGIN_CHIPS_ITEM_SIZE_BYTES = 48;
export const PLUGIN_CHIPS_SIZE_BYTES =
  PLUGIN_CHIPS_SIZE_ITEMS * PLUGIN_CHIPS_ITEM_SIZE_BYTES;
export const OUTFIT_CONFIG_SIZE_BYTES = 48;
export const PLAY_RECORDS_SIZE_BYTES = 28;
export const POD_COSMETIC_CONFIG_SIZE_BYTES = 12;
export const HAIR_COLORS_SIZE_BYTES = 3;
export const EMIL_BULLETS_EQUIPPED_SIZE_BYTES = 1;
export const WEAPON_SLOT_SIZE_BYTES = 8;
export const POD_CONFIG_SIZE_BYTES = 24;

export const BEFORE_STEAM_ID_SIZE_BYTES = SAVEFILE_STEAM_ID_START_BYTE;
export const BETWEEN_STEAM_ID_AND_PLAY_TIME_START_BYTE =
  SAVEFILE_STEAM_ID_START_BYTE + STEAM_ID_SIZE_BYTES;
export const BETWEEN_STEAM_ID_AND_PLAY_TIME_SIZE_BYTES =
  SAVEFILE_PLAY_TIME_START_BYTE - BETWEEN_STEAM_ID_AND_PLAY_TIME_START_BYTE;
export const BETWEEN_PLAY_TIME_AND_CHARACTER_NAME_START_BYTE =
  SAVEFILE_PLAY_TIME_START_BYTE + PLAY_TIME_SIZE_BYTES;
export const BETWEEN_PLAY_TIME_AND_CHARACTER_NAME_SIZE_BYTES =
  SAVEFILE_CHARACTER_NAME_START_BYTE -
  BETWEEN_PLAY_TIME_AND_CHARACTER_NAME_START_BYTE;
export const BETWEEN_CHARACTER_NAME_AND_MONEY_START_BYTE =
  SAVEFILE_CHARACTER_NAME_START_BYTE + CHARACTER_NAME_SIZE_BYTES;
export const BETWEEN_CHARACTER_NAME_AND_MONEY_SIZE_BYTES =
  SAVEFILE_MONEY_START_BYTE - BETWEEN_CHARACTER_NAME_AND_MONEY_START_BYTE;

/** Gap between POD programs end and plug-in chips (NieREdit unknown6). */
export const BETWEEN_POD_AND_CHIPS_START_BYTE =
  SAVEFILE_POD_PROGRAMS_START_BYTE + POD_PROGRAMS_SIZE_BYTES;
export const BETWEEN_POD_AND_CHIPS_SIZE_BYTES =
  SAVEFILE_PLUGIN_CHIPS_START_BYTE - BETWEEN_POD_AND_CHIPS_START_BYTE;

export const BETWEEN_CHIPS_AND_OUTFIT_CONFIG_START_BYTE =
  SAVEFILE_PLUGIN_CHIPS_START_BYTE + PLUGIN_CHIPS_SIZE_BYTES;
export const BETWEEN_CHIPS_AND_OUTFIT_CONFIG_SIZE_BYTES =
  SAVEFILE_OUTFIT_CONFIG_START_BYTE -
  BETWEEN_CHIPS_AND_OUTFIT_CONFIG_START_BYTE;

export const BETWEEN_OUTFIT_CONFIG_AND_PLAY_RECORDS_START_BYTE =
  SAVEFILE_OUTFIT_CONFIG_START_BYTE + OUTFIT_CONFIG_SIZE_BYTES;
export const BETWEEN_OUTFIT_CONFIG_AND_PLAY_RECORDS_SIZE_BYTES =
  SAVEFILE_PLAY_RECORDS_START_BYTE -
  BETWEEN_OUTFIT_CONFIG_AND_PLAY_RECORDS_START_BYTE;

export const BETWEEN_PLAY_RECORDS_AND_POD_COSMETIC_CONFIG_START_BYTE =
  SAVEFILE_PLAY_RECORDS_START_BYTE + PLAY_RECORDS_SIZE_BYTES;
export const BETWEEN_PLAY_RECORDS_AND_POD_COSMETIC_CONFIG_SIZE_BYTES =
  SAVEFILE_POD_COSMETIC_CONFIG_START_BYTE -
  BETWEEN_PLAY_RECORDS_AND_POD_COSMETIC_CONFIG_START_BYTE;

export const BETWEEN_POD_COSMETIC_CONFIG_AND_HAIR_COLORS_START_BYTE =
  SAVEFILE_POD_COSMETIC_CONFIG_START_BYTE + POD_COSMETIC_CONFIG_SIZE_BYTES;
export const BETWEEN_POD_COSMETIC_CONFIG_AND_HAIR_COLORS_SIZE_BYTES =
  SAVEFILE_HAIR_COLORS_START_BYTE -
  BETWEEN_POD_COSMETIC_CONFIG_AND_HAIR_COLORS_START_BYTE;

export const BETWEEN_EMIL_BULLETS_AND_WEAPON_SLOTS_START_BYTE =
  SAVEFILE_EMIL_BULLETS_EQUIPPED_BYTE + EMIL_BULLETS_EQUIPPED_SIZE_BYTES;
export const BETWEEN_EMIL_BULLETS_AND_WEAPON_SLOTS_SIZE_BYTES =
  SAVEFILE_WEAPON_SLOT_1_START_BYTE -
  BETWEEN_EMIL_BULLETS_AND_WEAPON_SLOTS_START_BYTE;

export const BETWEEN_WEAPON_SLOTS_AND_XP_START_BYTE =
  SAVEFILE_WEAPON_SLOT_2_START_BYTE + WEAPON_SLOT_SIZE_BYTES;
export const BETWEEN_WEAPON_SLOTS_AND_XP_SIZE_BYTES =
  SAVEFILE_XP_START_BYTE - BETWEEN_WEAPON_SLOTS_AND_XP_START_BYTE;

export const BETWEEN_XP_AND_POD_CONFIG_START_BYTE =
  SAVEFILE_XP_START_BYTE + XP_SIZE_BYTES;
export const BETWEEN_XP_AND_POD_CONFIG_SIZE_BYTES =
  SAVEFILE_POD_CONFIG_START_BYTE - BETWEEN_XP_AND_POD_CONFIG_START_BYTE;

export const BETWEEN_POD_CONFIG_AND_DEBUG_FLAG_START_BYTE =
  SAVEFILE_POD_CONFIG_START_BYTE + POD_CONFIG_SIZE_BYTES;
export const BETWEEN_POD_CONFIG_AND_DEBUG_FLAG_SIZE_BYTES =
  SAVEFILE_DEBUG_FLAG_START_BYTE - BETWEEN_POD_CONFIG_AND_DEBUG_FLAG_START_BYTE;
export const AFTER_DEBUG_FLAG_START_BYTE =
  SAVEFILE_DEBUG_FLAG_START_BYTE + DEBUG_FLAG_SIZE_BYTES;
export const AFTER_DEBUG_FLAG_SIZE_BYTES =
  SAVEFILE_SIZE_BYTES - AFTER_DEBUG_FLAG_START_BYTE;
