export {
  AFTER_DEBUG_FLAG_SIZE_BYTES,
  AFTER_DEBUG_FLAG_START_BYTE,
  BEFORE_STEAM_ID_SIZE_BYTES,
  BETWEEN_CHARACTER_NAME_AND_MONEY_SIZE_BYTES,
  BETWEEN_CHARACTER_NAME_AND_MONEY_START_BYTE,
  BETWEEN_CHIPS_AND_OUTFIT_CONFIG_SIZE_BYTES,
  BETWEEN_CHIPS_AND_OUTFIT_CONFIG_START_BYTE,
  BETWEEN_EMIL_BULLETS_AND_WEAPON_SLOTS_SIZE_BYTES,
  BETWEEN_EMIL_BULLETS_AND_WEAPON_SLOTS_START_BYTE,
  BETWEEN_POD_AND_CHIPS_SIZE_BYTES,
  BETWEEN_POD_AND_CHIPS_START_BYTE,
  BETWEEN_PLAY_TIME_AND_CHARACTER_NAME_SIZE_BYTES,
  BETWEEN_PLAY_TIME_AND_CHARACTER_NAME_START_BYTE,
  BETWEEN_OUTFIT_CONFIG_AND_PLAY_RECORDS_SIZE_BYTES,
  BETWEEN_OUTFIT_CONFIG_AND_PLAY_RECORDS_START_BYTE,
  BETWEEN_PLAY_RECORDS_AND_POD_COSMETIC_CONFIG_SIZE_BYTES,
  BETWEEN_PLAY_RECORDS_AND_POD_COSMETIC_CONFIG_START_BYTE,
  BETWEEN_POD_COSMETIC_CONFIG_AND_HAIR_COLORS_SIZE_BYTES,
  BETWEEN_POD_COSMETIC_CONFIG_AND_HAIR_COLORS_START_BYTE,
  BETWEEN_POD_CONFIG_AND_DEBUG_FLAG_SIZE_BYTES,
  BETWEEN_POD_CONFIG_AND_DEBUG_FLAG_START_BYTE,
  BETWEEN_STEAM_ID_AND_PLAY_TIME_SIZE_BYTES,
  BETWEEN_STEAM_ID_AND_PLAY_TIME_START_BYTE,
  BETWEEN_WEAPON_SLOTS_AND_XP_SIZE_BYTES,
  BETWEEN_WEAPON_SLOTS_AND_XP_START_BYTE,
  BETWEEN_XP_AND_POD_CONFIG_SIZE_BYTES,
  BETWEEN_XP_AND_POD_CONFIG_START_BYTE,
  CHARACTER_NAME_SIZE_BYTES,
  DEBUG_FLAG_SIZE_BYTES,
  EMIL_BULLETS_EQUIPPED_SIZE_BYTES,
  HAIR_COLORS_SIZE_BYTES,
  INVENTORY_ITEM_SIZE_BYTES,
  INVENTORY_SIZE_BYTES,
  INVENTORY_SIZE_ITEMS,
  MONEY_SIZE_BYTES,
  OUTFIT_CONFIG_SIZE_BYTES,
  PLAY_RECORDS_SIZE_BYTES,
  PLAY_TIME_SIZE_BYTES,
  PLUGIN_CHIPS_ITEM_SIZE_BYTES,
  PLUGIN_CHIPS_SIZE_BYTES,
  PLUGIN_CHIPS_SIZE_ITEMS,
  POD_CONFIG_SIZE_BYTES,
  POD_COSMETIC_CONFIG_SIZE_BYTES,
  POD_PROGRAMS_ITEM_SIZE_BYTES,
  POD_PROGRAMS_SIZE_BYTES,
  POD_PROGRAMS_SIZE_ITEMS,
  PURCHASED_CHIP_CAPACITY_SIZE_BYTES,
  SAVEFILE_CHARACTER_NAME_START_BYTE,
  SAVEFILE_CORPSE_INVENTORY_START_BYTE,
  SAVEFILE_DEBUG_FLAG_START_BYTE,
  SAVEFILE_INVENTORY_START_BYTE,
  SAVEFILE_MONEY_START_BYTE,
  SAVEFILE_OUTFIT_CONFIG_START_BYTE,
  SAVEFILE_PLAY_TIME_START_BYTE,
  SAVEFILE_PLAY_RECORDS_START_BYTE,
  SAVEFILE_EMIL_BULLETS_EQUIPPED_BYTE,
  SAVEFILE_HAIR_COLORS_START_BYTE,
  SAVEFILE_PLUGIN_CHIPS_START_BYTE,
  SAVEFILE_POD_CONFIG_START_BYTE,
  SAVEFILE_POD_COSMETIC_CONFIG_START_BYTE,
  SAVEFILE_POD_PROGRAMS_START_BYTE,
  SAVEFILE_PURCHASED_CHIP_CAPACITY_START_BYTE,
  SAVEFILE_SIZE_BYTES,
  SAVEFILE_STEAM_ID_START_BYTE,
  SAVEFILE_WEAPON_SLOT_1_START_BYTE,
  SAVEFILE_WEAPON_SLOT_2_START_BYTE,
  SAVEFILE_WEAPONS_START_BYTE,
  SAVEFILE_XP_START_BYTE,
  STEAM_ID_SIZE_BYTES,
  WEAPONS_ITEM_SIZE_BYTES,
  WEAPONS_SIZE_BYTES,
  WEAPONS_SIZE_ITEMS,
  WEAPON_SLOT_SIZE_BYTES,
  XP_SIZE_BYTES,
} from "./constants";

export {
  InventoryItemStatusError,
  InventorySizeError,
  ITEM_STATUS_ACTIVE,
  ITEM_STATUS_INACTIVE,
  parseInventory,
  serializeInventory,
  setInventoryItem,
  setInventoryItemId,
  type InventoryItem,
  type ItemStatus,
} from "./inventory";

export {
  load,
  serialize,
  SlotDataSizeError,
  type SlotData,
} from "./slotData";

export {
  EMPTY_WEAPON_BYTES,
  parseWeaponItem,
  parseWeapons,
  replaceWeaponId,
  serializeWeaponItem,
  serializeWeapons,
  WeaponSizeError,
  writeWeaponAt,
  type WeaponItem,
} from "./weapons";

export {
  copyPluginChipLoadout,
  EMPTY_PLUGIN_CHIP_ID,
  equipPluginChipToLoadout,
  minimumWeightForLevel,
  optimizePluginChipLoadout,
  OsChipLockedError,
  OS_PLUGIN_CHIP_TYPE,
  parsePluginChips,
  pluginChipLoadoutUsedCost,
  PluginChipsSizeError,
  replacePluginChipType,
  serializePluginChips,
  setEquippedPluginChipWeight,
  setPluginChip,
  unequipPluginChipFromLoadout,
  VANILLA_PLUGIN_CHIP_IDS,
  type PluginChip,
  type PluginChipId,
  type PluginChipLoadoutSet,
  type PluginChipPatch,
} from "./pluginChips";

export {
  formatBestOfStatLine,
  formatStackableStatLine,
  summarizeEquippedChipStats,
  type BestOfStatLine,
  type ChipLoadoutStatsSummary,
  type ListedStatLine,
  type StackableStatLine,
} from "./chipLoadoutStats";

export {
  ACTIVE_CHIP_LOADOUT_SET_SUPPORTED,
  ActiveChipLoadoutSetUnsupportedError,
  getActiveChipLoadoutSet,
  setActiveChipLoadoutSet,
} from "./activeChipLoadoutSet";

export {
  EMPTY_POD_PROGRAM_ID,
  parsePodPrograms,
  POD_PROGRAM_IDS,
  PodProgramsSizeError,
  replacePodProgram,
  serializePodPrograms,
  setPodProgramId,
  type PodProgram,
} from "./podPrograms";

export { getMoney, setMoney } from "./money";
export {
  decodePurchasedCapacity,
  encodePurchasedCapacity,
  getPurchasedChipCapacity,
  purchasedCapacityTiers,
  PURCHASED_CAPACITY_OPTIONS,
  setPurchasedChipCapacity,
  type PurchasedCapacityTiers,
} from "./purchasedCapacity";
export {
  CAPACITY_EXPANSION_ITEM_IDS,
  setPurchasedChipCapacityWithInventorySync,
  syncInventoryCapacityExpansionItems,
} from "./capacityExpansionInventory";
export { getXp, setXp } from "./xp";
export {
  DEBUG_FLAG_VALUES,
  GeneralCoreValueError,
  getCharacterName,
  getDebugFlag,
  getPlayTime,
  getSteamId,
  setCharacterName,
  setDebugFlag,
  setPlayTime,
  setSteamId,
  type DebugFlagValue,
} from "./generalCore";
export { levelFromXp, setLevel, xpForLevel } from "./level";
export { MAX_LEVEL, XP_TABLE } from "./xpTable";

export {
  EMPTY_WEAPON_SLOT_ID,
  parseWeaponSlot,
  serializeWeaponSlot,
  setWeaponSlotAttack,
  WeaponSlotValueError,
  type WeaponSlot,
} from "./weaponSlots";

export {
  EMPTY_POD_CONFIG_PROGRAM_ID,
  parsePodConfig,
  POD_CONFIG_PROGRAM_IDS,
  PodConfigSizeError,
  PodConfigValueError,
  serializePodConfig,
  setPodConfigPod,
  type PodConfig,
  type PodConfigPatch,
  type PodConfigPod,
  type PodConfigProgram,
} from "./podConfig";

export {
  EmilBulletsSizeError,
  EmilBulletsValueError,
  parseEmilBulletsEquipped,
  parsePlayRecords,
  PlayRecordsSizeError,
  PlayRecordsValueError,
  serializeEmilBulletsEquipped,
  serializePlayRecords,
  setEmilBulletsEquipped,
  setPlayRecordCounter,
  type EditablePlayRecordCounter,
  type EmilBulletsEquipped,
  type PlayRecords,
} from "./playRecordsEmil";

export {
  CosmeticsSizeError,
  CosmeticsValueError,
  parseHairColors,
  parseOutfitConfig,
  parsePodCosmeticConfig,
  POD_COSMETIC_IDS,
  serializeHairColors,
  serializeOutfitConfig,
  serializePodCosmeticConfig,
  setDressModule,
  setHairColor,
  setHeadAccessory,
  setOutfit,
  setPodCosmetic,
  type Android,
  type HairColors,
  type OutfitConfig,
  type PodCosmeticConfig,
  type SerializedBooleanI32,
} from "./cosmetics";
